//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Midas.VeiculoZ.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class ConstantesDados {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ConstantesDados() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Midas.VeiculoZ.Recursos.ConstantesDados", typeof(ConstantesDados).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update abastecimento set idposto=@idposto, data=@data, observacoes=@observacoes, tanquecheio=@tanquecheio, idtipoabastecimento=@idtipoabastecimento, valor=@valor, valorlitro=@valorlitro where id = @id.
        /// </summary>
        internal static string AtualizarAbastecimento {
            get {
                return ResourceManager.GetString("AtualizarAbastecimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update classificacaoinfracao set descricao=@descricao, pontos=@pontos where id = @id.
        /// </summary>
        internal static string AtualizarClassificacaoInfracao {
            get {
                return ResourceManager.GetString("AtualizarClassificacaoInfracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update despesa set descricao=@descricao,data=@data,idempresa=@idempresa,idtipo=@idtipo, idveiculo=@idveiculo, valor=@valor where id=@id.
        /// </summary>
        internal static string AtualizarDespesa {
            get {
                return ResourceManager.GetString("AtualizarDespesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update distribuidora set nome = @nome where id = @id.
        /// </summary>
        internal static string AtualizarDistribuidora {
            get {
                return ResourceManager.GetString("AtualizarDistribuidora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update infracao set descricao=@descricao,artigo=@artigo,infrator=@infrator,valor=@valor,idclassificacao=@idclassificacao where id=@id.
        /// </summary>
        internal static string AtualizarInfracao {
            get {
                return ResourceManager.GetString("AtualizarInfracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update manutencao set data=@data, descricao=@descricao, km=@km, idveiculo=@idveiculo, lembrarpordata=@lembrarpordata, verificado=@verificado where id = @id.
        /// </summary>
        internal static string AtualizarManutencao {
            get {
                return ResourceManager.GetString("AtualizarManutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update multa set         ///
        ///data=@data,datavencimento=@datavencimento,idveiculo=@idveiculo,idinfracao=@idinfracao,local=@local,idsituacao=@idsituacao,observacoes=@observacoes where         ///
        ///id=@id.
        /// </summary>
        internal static string AtualizarMulta {
            get {
                return ResourceManager.GetString("AtualizarMulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update percurso set odometroinicial = @odometroinicial, odometrofinal = @odometrofinal, idveiculo=@idveiculo, viagem=@viagem, idabastecimentoinicial=@idabastecimentoinicial, idabastecimentofinal=@idabastecimentofinal, consumomedio=@consumomedio  where id = @id.
        /// </summary>
        internal static string AtualizarPercurso {
            get {
                return ResourceManager.GetString("AtualizarPercurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update posto set idpessoajuridica=@idpessoajuridica, iddistribuidora=@iddistribuidora, observacoes=@observacoes where id = @id.
        /// </summary>
        internal static string AtualizarPosto {
            get {
                return ResourceManager.GetString("AtualizarPosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update situacaomulta set nome=@nome where id = @id.
        /// </summary>
        internal static string AtualizarSituacaoMulta {
            get {
                return ResourceManager.GetString("AtualizarSituacaoMulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update tipocombustivel set nome = @nome where id = @id.
        /// </summary>
        internal static string AtualizarTipoCombustivel {
            get {
                return ResourceManager.GetString("AtualizarTipoCombustivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update tipodespesa set nome = @nome where id = @id.
        /// </summary>
        internal static string AtualizarTipoDespesa {
            get {
                return ResourceManager.GetString("AtualizarTipoDespesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update veiculo set placa=@placa, renavam=@renavam, cor=@cor, modelo=@modelo, marca=@marca where id = @id.
        /// </summary>
        internal static string AtualizarVeiculo {
            get {
                return ResourceManager.GetString("AtualizarVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from abastecimento where id = @id.
        /// </summary>
        internal static string ExcluirAbastecimento {
            get {
                return ResourceManager.GetString("ExcluirAbastecimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from classificacaoinfracao where id=@id.
        /// </summary>
        internal static string ExcluirClassificacaoInfracao {
            get {
                return ResourceManager.GetString("ExcluirClassificacaoInfracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from despesa where id = @id.
        /// </summary>
        internal static string ExcluirDespesa {
            get {
                return ResourceManager.GetString("ExcluirDespesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from distribuidora where id = @id.
        /// </summary>
        internal static string ExcluirDistribuidora {
            get {
                return ResourceManager.GetString("ExcluirDistribuidora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from infracao where id = @id.
        /// </summary>
        internal static string ExcluirInfracao {
            get {
                return ResourceManager.GetString("ExcluirInfracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from manutencao where id = @id.
        /// </summary>
        internal static string ExcluirManutencao {
            get {
                return ResourceManager.GetString("ExcluirManutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from multa where id =@id.
        /// </summary>
        internal static string ExcluirMulta {
            get {
                return ResourceManager.GetString("ExcluirMulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from percurso where id = @id.
        /// </summary>
        internal static string ExcluirPercurso {
            get {
                return ResourceManager.GetString("ExcluirPercurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from posto where id = @id.
        /// </summary>
        internal static string ExcluirPosto {
            get {
                return ResourceManager.GetString("ExcluirPosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from situacaomulta where id = @id.
        /// </summary>
        internal static string ExcluirSituacaoMulta {
            get {
                return ResourceManager.GetString("ExcluirSituacaoMulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from tipocombustivel where id = @id.
        /// </summary>
        internal static string ExcluirTipoCombustivel {
            get {
                return ResourceManager.GetString("ExcluirTipoCombustivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from tipodespesa where id = @id.
        /// </summary>
        internal static string ExcluirTipoDespesa {
            get {
                return ResourceManager.GetString("ExcluirTipoDespesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from veiculo where id = @id.
        /// </summary>
        internal static string ExcluirVeiculo {
            get {
                return ResourceManager.GetString("ExcluirVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE INDEX IdxPercursoVeiculo ON percurso (idveiculo).
        /// </summary>
        internal static string IndicePercursoVeiculo {
            get {
                return ResourceManager.GetString("IndicePercursoVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into abastecimento (idposto,data,observacoes,tanquecheio,idtipoabastecimento,valor,valorlitro) values (@idposto,@data,@observacoes,@tanquecheio,@idtipoabastecimento,@valor,@valorlitro).
        /// </summary>
        internal static string InserirAbastecimento {
            get {
                return ResourceManager.GetString("InserirAbastecimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into classificacaoinfracao (descricao,pontos) values (@descricao,@pontos).
        /// </summary>
        internal static string InserirClassificacaoInfracao {
            get {
                return ResourceManager.GetString("InserirClassificacaoInfracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into despesa (descricao,data,idempresa,valor,idtipo,idveiculo) values (@descricao,@data,@idempresa,@valor,@idtipo,@idveiculo).
        /// </summary>
        internal static string InserirDespesa {
            get {
                return ResourceManager.GetString("InserirDespesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into distribuidora (nome)values(@nome).
        /// </summary>
        internal static string InserirDistribuidora {
            get {
                return ResourceManager.GetString("InserirDistribuidora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into infracao (descricao,artigo,infrator,valor,idclassificacao) values (@descricao,@artigo,@infrator,@valor,@idclassificacao).
        /// </summary>
        internal static string InserirInfracao {
            get {
                return ResourceManager.GetString("InserirInfracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into manutencao (idveiculo,data,descricao,km,lembrarpordata,verificado) values (@idveiculo,@data,@descricao,@km,@lembrarpordata,@verificado).
        /// </summary>
        internal static string InserirManutencao {
            get {
                return ResourceManager.GetString("InserirManutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into multa (data,datavencimento,idveiculo,idinfracao,local,idsituacao,observacoes) values         ///
        ///(@data,@datavencimento,@idveiculo,@idinfracao,@local,@idsituacao,@observacoes).
        /// </summary>
        internal static string InserirMulta {
            get {
                return ResourceManager.GetString("InserirMulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into percurso (odometroinicial,odometrofinal,idveiculo,viagem,idabastecimentoinicial,idabastecimentofinal,consumomedio) values (@odometroinicial,@odometrofinal,@idveiculo,@viagem,@idabastecimentoinicial,@idabastecimentofinal,@consumomedio).
        /// </summary>
        internal static string InserirPercurso {
            get {
                return ResourceManager.GetString("InserirPercurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into posto (idpessoajuridica,iddistribuidora,observacoes) values (@idpessoajuridica, @iddistribuidora, @observacoes).
        /// </summary>
        internal static string InserirPosto {
            get {
                return ResourceManager.GetString("InserirPosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into situacaomulta (nome) values (@nome).
        /// </summary>
        internal static string InserirSituacaoMulta {
            get {
                return ResourceManager.GetString("InserirSituacaoMulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into tipocombustivel (nome) values (@nome).
        /// </summary>
        internal static string InserirTipoCombustivel {
            get {
                return ResourceManager.GetString("InserirTipoCombustivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into tipodespesa (nome) values (@nome).
        /// </summary>
        internal static string InserirTipoDespesa {
            get {
                return ResourceManager.GetString("InserirTipoDespesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into veiculo(placa,renavam,cor,modelo,marca) values (@placa,@renavam,@cor,@modelo,@marca).
        /// </summary>
        internal static string InserirVeiculo {
            get {
                return ResourceManager.GetString("InserirVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from abastecimento where id = @id.
        /// </summary>
        internal static string SelecionarAbastecimento {
            get {
                return ResourceManager.GetString("SelecionarAbastecimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from classificacaoinfracao where id = @id.
        /// </summary>
        internal static string SelecionarClassificacaoInfracao {
            get {
                return ResourceManager.GetString("SelecionarClassificacaoInfracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from despesa where id=@id.
        /// </summary>
        internal static string SelecionarDespesa {
            get {
                return ResourceManager.GetString("SelecionarDespesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from despesa where idveiculo=@idveiculo order by data desc.
        /// </summary>
        internal static string SelecionarDespesasPorVeiculo {
            get {
                return ResourceManager.GetString("SelecionarDespesasPorVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from distribuidora where id = @id.
        /// </summary>
        internal static string SelecionarDistribuidora {
            get {
                return ResourceManager.GetString("SelecionarDistribuidora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select sum(valor) as total from abastecimento where id in (select idabastecimentoinicial from percurso where idveiculo = @idveiculo).
        /// </summary>
        internal static string SelecionarGastoTotalPorVeiculo {
            get {
                return ResourceManager.GetString("SelecionarGastoTotalPorVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select idabastecimentofinal from percurso where id = @id.
        /// </summary>
        internal static string SelecionarIdAbastecimentoFinalPercurso {
            get {
                return ResourceManager.GetString("SelecionarIdAbastecimentoFinalPercurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from infracao where id = @id.
        /// </summary>
        internal static string SelecionarInfracao {
            get {
                return ResourceManager.GetString("SelecionarInfracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from infracao where idclassificacao=@idclassificacao.
        /// </summary>
        internal static string SelecionarInfracoesPorClassificacao {
            get {
                return ResourceManager.GetString("SelecionarInfracoesPorClassificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from manuntencao where id = @id.
        /// </summary>
        internal static string SelecionarManutencao {
            get {
                return ResourceManager.GetString("SelecionarManutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from manutencao where idveiculo=@idveiculo and verificado=0 and data &lt;= @data and lembrarpordata = 1.
        /// </summary>
        internal static string SelecionarManutencoesPorDataVeiculoNaoVerificados {
            get {
                return ResourceManager.GetString("SelecionarManutencoesPorDataVeiculoNaoVerificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from manutencao where idveiculo=@idveiculo and verificado=0 and km &lt;= @km and lembrarpordata = 0 and km &gt; 0.
        /// </summary>
        internal static string SelecionarManutencoesPorKMVeiculoNaoVerificados {
            get {
                return ResourceManager.GetString("SelecionarManutencoesPorKMVeiculoNaoVerificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from multa where id = @id.
        /// </summary>
        internal static string SelecionarMulta {
            get {
                return ResourceManager.GetString("SelecionarMulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from multa where idveiculo = @idveiculo order by data desc.
        /// </summary>
        internal static string SelecionarMultasPorVeiculo {
            get {
                return ResourceManager.GetString("SelecionarMultasPorVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id,odometroinicial,odometrofinal,idveiculo,viagem,idabastecimentoinicial,idabastecimentofinal from percurso where id = @id.
        /// </summary>
        internal static string SelecionarPercurso {
            get {
                return ResourceManager.GetString("SelecionarPercurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from percurso where idabastecimentofinal = @idabastecimentofinal order by id.
        /// </summary>
        internal static string SelecionarPercursosPorAbastecimentoFinal {
            get {
                return ResourceManager.GetString("SelecionarPercursosPorAbastecimentoFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from percurso where viagem = 0 and idveiculo = @idveiculo and idabastecimentoinicial &gt; 0 and idabastecimentofinal &gt; 0 order by consumomedio asc.
        /// </summary>
        internal static string SelecionarPercursosPorConsumoMedioAscendente {
            get {
                return ResourceManager.GetString("SelecionarPercursosPorConsumoMedioAscendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from percurso where viagem = 0 and idveiculo = @idveiculo and idabastecimentoinicial &gt; 0 and idabastecimentofinal &gt; 0 order by consumomedio desc.
        /// </summary>
        internal static string SelecionarPercursosPorConsumoMedioDescendente {
            get {
                return ResourceManager.GetString("SelecionarPercursosPorConsumoMedioDescendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from percurso 
        ///	where   idveiculo = @idveiculo and 
        ///		idabastecimentoinicial in (select id from abastecimento where data &gt;= @data1 and data &lt;= @data2) and
        ///        (
        ///		idabastecimentoinicial in (select id from abastecimento where idposto = @idposto) or
        ///		idabastecimentoinicial in (select id from abastecimento where idtipoabastecimento = @idtipocombustivel)
        ///        ).
        /// </summary>
        internal static string SelecionarPercursosPorFiltro {
            get {
                return ResourceManager.GetString("SelecionarPercursosPorFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from percurso where idveiculo = @idveiculo order by id desc.
        /// </summary>
        internal static string SelecionarPercursosPorVeiculo {
            get {
                return ResourceManager.GetString("SelecionarPercursosPorVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id,iddistribuidora,idpessoajuridica,observacoes from posto where id =@id.
        /// </summary>
        internal static string SelecionarPosto {
            get {
                return ResourceManager.GetString("SelecionarPosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from situacaomulta where id = @id.
        /// </summary>
        internal static string SelecionarSituacaoMulta {
            get {
                return ResourceManager.GetString("SelecionarSituacaoMulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from tipocombustivel where id = @id.
        /// </summary>
        internal static string SelecionarTipoCombustivel {
            get {
                return ResourceManager.GetString("SelecionarTipoCombustivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from tipodespesa where id = @id.
        /// </summary>
        internal static string SelecionarTipoDespesa {
            get {
                return ResourceManager.GetString("SelecionarTipoDespesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from classificacaoinfracao order by descricao.
        /// </summary>
        internal static string SelecionarTodasClassificacoesInfracao {
            get {
                return ResourceManager.GetString("SelecionarTodasClassificacoesInfracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from despesa order by data.
        /// </summary>
        internal static string SelecionarTodasDespesas {
            get {
                return ResourceManager.GetString("SelecionarTodasDespesas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from distribuidora order by nome.
        /// </summary>
        internal static string SelecionarTodasDistribuidoras {
            get {
                return ResourceManager.GetString("SelecionarTodasDistribuidoras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from infracao order by descricao.
        /// </summary>
        internal static string SelecionarTodasInfracoes {
            get {
                return ResourceManager.GetString("SelecionarTodasInfracoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from manutencao where idveiculo=@idveiculo order by id desc.
        /// </summary>
        internal static string SelecionarTodasManutencoesPorVeiculo {
            get {
                return ResourceManager.GetString("SelecionarTodasManutencoesPorVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from multa order by data.
        /// </summary>
        internal static string SelecionarTodasMultas {
            get {
                return ResourceManager.GetString("SelecionarTodasMultas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from situacaomulta order by nome.
        /// </summary>
        internal static string SelecionarTodasSituacoesMulta {
            get {
                return ResourceManager.GetString("SelecionarTodasSituacoesMulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from abastecimento order by data desc.
        /// </summary>
        internal static string SelecionarTodosAbastecimentos {
            get {
                return ResourceManager.GetString("SelecionarTodosAbastecimentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id,odometroinicial,odometrofinal,idveiculo,viagem,idabastecimentoinicial,idabastecimentofinal from percurso order by id desc.
        /// </summary>
        internal static string SelecionarTodosPercursos {
            get {
                return ResourceManager.GetString("SelecionarTodosPercursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id,iddistribuidora,idpessoajuridica,observacoes from posto order by id desc.
        /// </summary>
        internal static string SelecionarTodosPostos {
            get {
                return ResourceManager.GetString("SelecionarTodosPostos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from tipocombustivel order by nome.
        /// </summary>
        internal static string SelecionarTodosTiposCombustivel {
            get {
                return ResourceManager.GetString("SelecionarTodosTiposCombustivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from tipodespesa order by nome.
        /// </summary>
        internal static string SelecionarTodosTiposDespesa {
            get {
                return ResourceManager.GetString("SelecionarTodosTiposDespesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from veiculo order by modelo.
        /// </summary>
        internal static string SelecionarTodosVeiculos {
            get {
                return ResourceManager.GetString("SelecionarTodosVeiculos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select sum(odometrofinal-odometroinicial) as total from percurso where idveiculo=@idveiculo and odometrofinal &gt; 0.
        /// </summary>
        internal static string SelecionarTotalKMPorVeiculo {
            get {
                return ResourceManager.GetString("SelecionarTotalKMPorVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select sum(valor/valorlitro) as total from abastecimento where id in (select idabastecimentoinicial from percurso where idveiculo = @idveiculo).
        /// </summary>
        internal static string SelecionarTotalLitrosPorVeiculo {
            get {
                return ResourceManager.GetString("SelecionarTotalLitrosPorVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from percurso where id 
        ///	IN (select max(id) from percurso where idveiculo=@idveiculo and 
        ///	idabastecimentoinicial IN (
        ///		select idabastecimentoinicial from abastecimento where data IN 
        ///			(select max(data) from abastecimento)
        ///	)).
        /// </summary>
        internal static string SelecionarUltimoPercursoPorVeiculo {
            get {
                return ResourceManager.GetString("SelecionarUltimoPercursoPorVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from veiculo where id = @id.
        /// </summary>
        internal static string SelecionarVeiculo {
            get {
                return ResourceManager.GetString("SelecionarVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table abastecimento (id int identity(1,1) not null primary key, idposto int references posto(id), data datetime, observacoes ntext, tanquecheio bit, idtipoabastecimento int references tipocombustivel(id), valor decimal, valorlitro decimal).
        /// </summary>
        internal static string TabelaAbastecimento {
            get {
                return ResourceManager.GetString("TabelaAbastecimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table despesa (id int identity(1,1) not null primary key, descricao nvarchar(255), data datetime, idempresa int, valor decimal, idtipo int references tipodespesa(id), idveiculo int references veiculo(id)).
        /// </summary>
        internal static string TabelaDespesa {
            get {
                return ResourceManager.GetString("TabelaDespesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table distribuidora (id int identity(1,1) not null primary key, nome nvarchar(80)).
        /// </summary>
        internal static string TabelaDistribuidora {
            get {
                return ResourceManager.GetString("TabelaDistribuidora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table manutencao (id int identity(1,1) not null primary key,data datetime,descricao nvarchar(255),km decimal,idveiculo int references veiculo(id), lembrarpordata bit, verificado bit).
        /// </summary>
        internal static string TabelaManutencao {
            get {
                return ResourceManager.GetString("TabelaManutencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table multa (
        ///	id int identity(1,1) not null primary key,
        ///	data datetime not null,
        ///	datavencimento datetime,
        ///	idveiculo int references Veiculo(id),
        ///	idinfracao int,
        ///	local nvarchar(255),
        ///	idsituacao int references SituacaoMulta(id),
        ///	observacoes ntext
        ///).
        /// </summary>
        internal static string TabelaMulta {
            get {
                return ResourceManager.GetString("TabelaMulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table percurso (id int identity(1,1) not null primary key, odometroinicial bigint, odometrofinal bigint, idveiculo int references veiculo(id), viagem bit, idabastecimentoinicial int references abastecimento(id), idabastecimentofinal int references abastecimento(id),consumomedio decimal).
        /// </summary>
        internal static string TabelaPercurso {
            get {
                return ResourceManager.GetString("TabelaPercurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table posto (id int identity(1,1) not null primary key, iddistribuidora int references distribuidora(id),idpessoajuridica int, observacoes nvarchar(255)).
        /// </summary>
        internal static string TabelaPosto {
            get {
                return ResourceManager.GetString("TabelaPosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table situacaomulta (
        ///	id int identity(1,1) not null primary key,
        ///	nome nvarchar(60)
        ///).
        /// </summary>
        internal static string TabelaSituacaoMulta {
            get {
                return ResourceManager.GetString("TabelaSituacaoMulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table tipocombustivel (id int identity(1,1) not null primary key, nome nvarchar(50)).
        /// </summary>
        internal static string TabelaTipoCombustivel {
            get {
                return ResourceManager.GetString("TabelaTipoCombustivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table tipodespesa(id int identity(1,1) not null primary key, nome nvarchar(100)).
        /// </summary>
        internal static string TabelaTipoDespesa {
            get {
                return ResourceManager.GetString("TabelaTipoDespesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table veiculo(id int identity(1,1) not null primary key, placa nvarchar(10), renavam nvarchar(20), cor nvarchar(20), modelo nvarchar(100), marca nvarchar(100)).
        /// </summary>
        internal static string TabelaVeiculo {
            get {
                return ResourceManager.GetString("TabelaVeiculo", resourceCulture);
            }
        }
    }
}
