//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Midas.Financeiro.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ComandosSQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ComandosSQL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Midas.Financeiro.Recursos.ComandosSQL", typeof(ComandosSQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update categorias set descricao = @descricao, idcategoriapai = @idcategoriapai where id = @id.
        /// </summary>
        public static string AtualizarCategoria {
            get {
                return ResourceManager.GetString("AtualizarCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into categorias (descricao,idcategoriapai) values (@descricao,@idcategoriapai).
        /// </summary>
        public static string InserirCategoria {
            get {
                return ResourceManager.GetString("InserirCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into contas (descricao,valorinicial) values (@descricao,@valorinicial).
        /// </summary>
        public static string InserirConta {
            get {
                return ResourceManager.GetString("InserirConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table categorias (id int identity(1,1) primary key, descricao nvarchar(50), idcategoriapai int).
        /// </summary>
        public static string TabelaCategoria {
            get {
                return ResourceManager.GetString("TabelaCategoria", resourceCulture);
            }
        }
    }
}
