//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Midas.Nucleo.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class ConstantesDados {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ConstantesDados() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Midas.Nucleo.Recursos.ConstantesDados", typeof(ConstantesDados).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update cidade set nome=@nome, idestado=@idestado where id=@id.
        /// </summary>
        internal static string AtualizarCidade {
            get {
                return ResourceManager.GetString("AtualizarCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update endereco set logradouro=@logradouro, numero=@numero, bairro=@bairro, codigopostal=@codigopostal,complemento=@complemento,idcidade=@idcidade where id=@id.
        /// </summary>
        internal static string AtualizarEndereco {
            get {
                return ResourceManager.GetString("AtualizarEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update estado set nome=@nome,idpais=@idpais where id=@id.
        /// </summary>
        internal static string AtualizarEstado {
            get {
                return ResourceManager.GetString("AtualizarEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update pais set nome=@nome where id=@id.
        /// </summary>
        internal static string AtualizarPais {
            get {
                return ResourceManager.GetString("AtualizarPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update pessoajuridica set cnpj = @cnpj, nomefantasia = @nomefantasia, idendereco=@idendereco where id = @id.
        /// </summary>
        internal static string AtualizarPessoaJuridica {
            get {
                return ResourceManager.GetString("AtualizarPessoaJuridica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from cidade where id=@id.
        /// </summary>
        internal static string ExcluirCidade {
            get {
                return ResourceManager.GetString("ExcluirCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from endereco where id = @id.
        /// </summary>
        internal static string ExcluirEndereco {
            get {
                return ResourceManager.GetString("ExcluirEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from estado where id =@id.
        /// </summary>
        internal static string ExcluirEstado {
            get {
                return ResourceManager.GetString("ExcluirEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from pais where id=@id.
        /// </summary>
        internal static string ExcluirPais {
            get {
                return ResourceManager.GetString("ExcluirPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from pessoajuridica where id = @id.
        /// </summary>
        internal static string ExcluirPessoaJuridica {
            get {
                return ResourceManager.GetString("ExcluirPessoaJuridica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into cidade (nome,idestado) values (@nome,@idestado).
        /// </summary>
        internal static string InserirCidade {
            get {
                return ResourceManager.GetString("InserirCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into endereco (logradouro,numero,bairro,codigopostal,complemento,idcidade) values (@logradouro,@numero,@bairro,@codigopostal,@complemento,@idcidade).
        /// </summary>
        internal static string InserirEndereco {
            get {
                return ResourceManager.GetString("InserirEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into estado (nome,idpais) values (@nome,@idpais).
        /// </summary>
        internal static string InserirEstado {
            get {
                return ResourceManager.GetString("InserirEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into pais(nome) values (@nome).
        /// </summary>
        internal static string InserirPais {
            get {
                return ResourceManager.GetString("InserirPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into pessoajuridica (cnpj,nomefantasia,idendereco) values (@cnpj,@nomefantasia,@idendereco).
        /// </summary>
        internal static string InserirPessoaJuridica {
            get {
                return ResourceManager.GetString("InserirPessoaJuridica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id,nome,idestado from cidade where id=@id.
        /// </summary>
        internal static string SelecionarCidade {
            get {
                return ResourceManager.GetString("SelecionarCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from endereco where id=@id.
        /// </summary>
        internal static string SelecionarEndereco {
            get {
                return ResourceManager.GetString("SelecionarEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id,nome,idpais from estado where id=@id.
        /// </summary>
        internal static string SelecionarEstado {
            get {
                return ResourceManager.GetString("SelecionarEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id, nome from pais where id = @id.
        /// </summary>
        internal static string SelecionarPais {
            get {
                return ResourceManager.GetString("SelecionarPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from pessoajuridica where id = @id.
        /// </summary>
        internal static string SelecionarPessoaJuridica {
            get {
                return ResourceManager.GetString("SelecionarPessoaJuridica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id,nome,idestado from cidade order by nome.
        /// </summary>
        internal static string SelecionarTodasCidades {
            get {
                return ResourceManager.GetString("SelecionarTodasCidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from pessoajuridica order by nomefantasia.
        /// </summary>
        internal static string SelecionarTodasPessoasJuridicas {
            get {
                return ResourceManager.GetString("SelecionarTodasPessoasJuridicas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from endereco order by logradouro.
        /// </summary>
        internal static string SelecionarTodosEnderecos {
            get {
                return ResourceManager.GetString("SelecionarTodosEnderecos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id,nome,idpais from estado order by nome.
        /// </summary>
        internal static string SelecionarTodosEstados {
            get {
                return ResourceManager.GetString("SelecionarTodosEstados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id,nome from pais order by nome.
        /// </summary>
        internal static string SelecionarTodosPaises {
            get {
                return ResourceManager.GetString("SelecionarTodosPaises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table cidade (id int identity(1,1) not null primary key, nome nvarchar(255), idestado int).
        /// </summary>
        internal static string TabelaCidade {
            get {
                return ResourceManager.GetString("TabelaCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table endereco (id int identity (1,1) not null primary key, logradouro nvarchar(255), numero nvarchar(10), bairro nvarchar(255), codigopostal nvarchar(50), complemento nvarchar(255), idcidade int).
        /// </summary>
        internal static string TabelaEndereco {
            get {
                return ResourceManager.GetString("TabelaEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table estado (id int identity(1,1) not null primary key, nome nvarchar(255), idpais int).
        /// </summary>
        internal static string TabelaEstado {
            get {
                return ResourceManager.GetString("TabelaEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table pais (id int identity(1,1) not null primary key, nome nvarchar(255)).
        /// </summary>
        internal static string TabelaPais {
            get {
                return ResourceManager.GetString("TabelaPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table pessoajuridica (id int identity(1,1) not null primary key, cnpj nvarchar(20), nomefantasia nvarchar(255),idendereco int).
        /// </summary>
        internal static string TabelaPessoaJuridica {
            get {
                return ResourceManager.GetString("TabelaPessoaJuridica", resourceCulture);
            }
        }
    }
}
