//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Midas.Nucleo.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConstantesGerais {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConstantesGerais() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Midas.Nucleo.Recursos.ConstantesGerais", typeof(ConstantesGerais).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midas.Financeiro.
        /// </summary>
        public static string BancoFinanceiro {
            get {
                return ResourceManager.GetString("BancoFinanceiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midas.VeiculoZ.Infracoes.
        /// </summary>
        public static string BancoInfracoes {
            get {
                return ResourceManager.GetString("BancoInfracoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midas.Nucleo.
        /// </summary>
        public static string BancoNucleo {
            get {
                return ResourceManager.GetString("BancoNucleo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midas.VeiculoZ.
        /// </summary>
        public static string BancoVeiculoZ {
            get {
                return ResourceManager.GetString("BancoVeiculoZ", resourceCulture);
            }
        }
    }
}
